### ISSUE TITLE
Cannot find module 'calipers-png' when using npm v5.2.0

### ISSUE THREAD

**Issue by jpuncle** [borodean/assets#6] opened 2017-07-28 06:53 UTC
Env:
* node v8.1.4
* npm v5.2.0

Errors:
```
Error: Cannot find module 'calipers-png'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /Users/xxx/test/node_modules/calipers/lib/index.js:32:14
    at Array.map (native)
    at module.exports (/Users/xxx/test/node_modules/calipers/lib/index.js:28:22)
    at Object.<anonymous> (/Users/xxx/test/node_modules/assets/lib/size.js:1:97)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

Reasons:
these code in the `assets/lib/size.js` caused the problems
```javascript
var calipers = require('calipers')('webp', 'png', 'jpeg', 'gif', 'svg');
```
In the calipers
```javascript
module.exports = function () {
  var args = Array.prototype.slice.call(arguments);

  var plugins = args.map(function (arg) {
    if (typeof arg === 'object') {
      return arg;
    } else {
      return require('calipers-' + arg);
    }
  });

  return {
    measure: measure.bind(null, plugins)
  };
};
```

But, the installed packages are the followwings:
```
$ ls node_modules/                                                    
assets           calipers         inflight         once
async            calipers-svg     inherits         path-is-absolute
balanced-match   calipers-webp    lodash           wrappy
bluebird         concat-map       mime
brace-expansion  glob             minimatch
```
And 
```
$ ls node_modules/assets/node_modules/                                
calipers-gif  calipers-jpeg calipers-png
```

So. `calipers` in `node_modules/` couldn't find `calipers-png` in `node_modules/assets/node_modules/`.

The solutions:
```
var webp = require('calipers-webp');
var png = require('calipers-png');
var jpeg = require('calipers-jpeg');
var gif = require('calipers-gif');
var svg = require('calipers-svg');
var calipers = require('calipers')(webp, png, jpeg, gif, svg);
```

**Comment by jpuncle** [comment] 2017-07-28 07:37
@borodean

**Comment by borodean** [comment] 2017-07-28 19:08
@mgartner, do you have any ideas?

**Comment by mgartner** [comment] 2017-07-28 21:54
That's odd. I guess something is wrong with requiring modules nested under `assets`? I'm not sure why that wouldn't work.

I've been thinking that separate modules for each file type in calipers is actually more trouble than it's worth, and there are other ways to solve some of the problems I was trying to solve when I broke them up into different modules. I'd like to bring them all back together into the same module, and release as a new major version, but not sure when I'll find the time for that.

**Comment by fooger** [comment] 2017-12-26 05:25
Confirm the error

**Comment by Maksym9669** [comment] 2018-12-16 01:21
Cannot find module @babel:

I've been facing this issue a couple of times. After installing some of the packages and writing some code with them I have this kind of error: "Uncaught Error: Cannot find module 

'C:\Users\max\Documents\WebDev\React\react_tinker\react_fb_clientpanel\node_modules\babel-preset-react-app\node_modules\@babel\runtime/helpers/slicedToArray'". 

Last time I solved it by manually inserting a file into that directory, but the question is why this is hapening? I am not doing anything different from what Brad does.

**Comment by borodean** [comment] 2018-12-18 13:17
@fooger could you please check whether the problem is gone in `assets@3.0.1`? I assume that https://github.com/borodean/assets/pull/8 should have fixed this.

**Comment by borodean** [comment] 2018-12-18 13:19
Fixed by https://github.com/borodean/assets/pull/8 in `assets@3.0.1`.

**Closed by borodean** 2018-12-18 13:19 UTC
Labels: bug
